In [1]:
import pandas as pd
import os
dir_name="C:/Users/namra/Practicum Dataset/user_data/user01/1598832660/"

In [2]:
dir = os.listdir( dir_name+'mMag' )
df_list = []

for file in dir:
   df = pd.read_csv(dir_name+"mMag/"+file)
   df['timestamp_s'] = float(os.path.splitext(file)[0])
   df = df.rename(columns={'x': 'mMag_x','y': 'mMag_y','z': 'mMag_z'})
   #df.to_csv(dir_name+"mMag/"+file,index=False)
   df_list.append(df)

df_csv_append = pd.concat(df_list, ignore_index=True)
df_csv_append.to_csv(dir_name+"1598832660_mMag.csv",index=False)

In [11]:
dir = os.listdir( dir_name+"mAcc" )
df_list = []

for file in dir:
   df = pd.read_csv(dir_name+"mAcc/"+file)
   df['timestamp_s'] = float(os.path.splitext(file)[0])
   df = df.rename(columns={'x': 'mAcc_x','y': 'mAcc_y','z': 'mAcc_z'})
   #df.to_csv(dir_name+"mAcc/"+file,index=False)
   df_list.append(df)

df_csv_append = pd.concat(df_list, ignore_index=True)
df_csv_append
df_csv_append.to_csv(dir_name+"1598832660_mAcc.csv",index=False)

In [3]:
dir = os.listdir( dir_name+"mGyr" )
df_list = []

for file in dir:
   df = pd.read_csv(dir_name+"mGyr/"+file)
   df['timestamp_s'] = float(os.path.splitext(file)[0])
   df = df.rename(columns={'x': 'mGyr_x','y': 'mGyr_y','z': 'mGyr_z','roll':'mGyr_roll','pitch':'mGyr_pitch', 'yaw':'mGyr_yaw'})
   #df.to_csv(dir_name+"mGyr/"+file,index=False)
   df_list.append(df)

df_csv_append = pd.concat(df_list, ignore_index=True)
df_csv_append.to_csv(dir_name+"1598832660_mGyr.csv",index=False)

In [4]:
dir = os.listdir( dir_name+"mGps" )
df_list = []

for file in dir:
   df = pd.read_csv(dir_name+"mGps/"+file)
   df['timestamp_s'] = float(os.path.splitext(file)[0])
   df = df.rename(columns={'lat': 'mGps_lat','lon': 'mGps_lon','accuracy': 'mGps_accr'})
   #df.to_csv(dir_name+"mGps/"+file,index=False)
   df_list.append(df)

df_csv_append = pd.concat(df_list, ignore_index=True)
df_csv_append.to_csv(dir_name+"1598832660_mGps.csv",index=False)

In [5]:
dir = os.listdir( dir_name+"e4Acc" )
df_list = []

for file in dir:
   df = pd.read_csv(dir_name+"e4Acc/"+file)
   df['timestamp_s'] = float(os.path.splitext(file)[0])
   df = df.rename(columns={'x': 'e4Acc_x','y': 'e4Acc_y','z': 'e4Acc_z'})
   #df.to_csv(dir_name+"e4Acc/"+file,index=False)
   df_list.append(df)

df_csv_append = pd.concat(df_list, ignore_index=True)
df_csv_append
df_csv_append.to_csv(dir_name+"1598832660_e4Acc.csv",index=False)

In [6]:
dir = os.listdir( dir_name+'e4Bvp' )
df_list = []

for file in dir:
   df = pd.read_csv(dir_name+"e4Bvp/"+file)
   df['timestamp_s'] = float(os.path.splitext(file)[0])
   df = df.rename(columns={'value': 'e4Bvp_val'})
   #df.to_csv(dir_name+"e4Bvp/"+file,index=False)
   df_list.append(df)

df_csv_append = pd.concat(df_list, ignore_index=True)
df_csv_append.to_csv(dir_name+"1598832660_e4Bvp.csv",index=False)

In [7]:
dir = os.listdir( dir_name+'e4Eda' )
df_list = []

for file in dir:
   df = pd.read_csv(dir_name+"e4Eda/"+file)
   df['timestamp_s'] = float(os.path.splitext(file)[0])
   df = df.rename(columns={'eda': 'e4Eda_val'})
   #df.to_csv(dir_name+"e4Eda/"+file,index=False)
   df_list.append(df)

df_csv_append = pd.concat(df_list, ignore_index=True)
df_csv_append.to_csv(dir_name+"1598832660_e4Eda.csv",index=False)

In [8]:
dir = os.listdir( dir_name+'e4Hr' )
df_list = []

for file in dir:
   df = pd.read_csv(dir_name+"e4Hr/"+file)
   df['timestamp_s'] = float(os.path.splitext(file)[0])
   df = df.rename(columns={'hr': 'e4Hr_val'})
   #df.to_csv(dir_name+"e4Hr/"+file,index=False)
   df_list.append(df)

df_csv_append = pd.concat(df_list, ignore_index=True)
df_csv_append.to_csv(dir_name+"1598832660_e4Hr.csv",index=False)

In [9]:
dir = os.listdir( dir_name+'e4Temp' )
df_list = []

for file in dir:
   df = pd.read_csv(dir_name+"e4Temp/"+file)
   df['timestamp_s'] = float(os.path.splitext(file)[0])
   df = df.rename(columns={'temp': 'e4Temp_val'})
   #df.to_csv(dir_name+"e4Temp/"+file,index=False)
   df_list.append(df)

df_csv_append = pd.concat(df_list, ignore_index=True)
df_csv_append.to_csv(dir_name+"1598832660_e4Temp.csv",index=False)

In [12]:
df = pd.read_csv(dir_name+"1598832660_mAcc.csv")
df['timestamp_s']=df['timestamp_s'].astype('int64')
df['timestamp']=df['timestamp']*1000
df['timestamp']=df['timestamp'].astype('int64')
df['timestamp_s']=df['timestamp_s']*1000
df['timestamp']=df['timestamp_s']+df['timestamp']
df.drop(columns=['timestamp_s'],inplace=True)
df.to_csv(dir_name+"1598832660_mAcc.csv",index=False)
df

             timestamp    mAcc_x    mAcc_y    mAcc_z
0        1598832660004  0.069434 -0.069434  9.703996
1        1598832660016  0.079011 -0.062251  9.701602
2        1598832660051  0.079011 -0.081405  9.696813
3        1598832660082  0.086194 -0.071828  9.682447
4        1598832660121  0.074223 -0.086194  9.718362
...                ...       ...       ...       ...
1292247  1598879919387  5.399090  0.081405  8.087860
1292248  1598879919420  5.399090  0.064645  8.097438
1292249  1598879919447  5.389513  0.062251  8.075889
1292250  1598879919488  5.389513  0.069434  8.075889
1292251  1598879919517  5.394301  0.088588  8.083072

[1292252 rows x 4 columns]

In [13]:
df = pd.read_csv(dir_name+"1598832660_mMag.csv")
df['timestamp_s']=df['timestamp_s'].astype('int64')
df['timestamp']=df['timestamp']*1000
df['timestamp']=df['timestamp'].astype('int64')
df['timestamp_s']=df['timestamp_s']*1000
df['timestamp']=df['timestamp_s']+df['timestamp']
df.drop(columns=['timestamp_s'],inplace=True)
df.to_csv(dir_name+"1598832660_mMag.csv",index=False)
df

             timestamp     mMag_x  mMag_y     mMag_z
0        1598832660015  -11.20000   -15.7 -70.900000
1        1598832660061  -11.20000   -15.8 -70.800000
2        1598832660091  -11.10000   -15.7 -70.800000
3        1598832660131  -11.20000   -15.8 -70.700005
4        1598832660152  -11.10000   -15.8 -70.800000
...                ...        ...     ...        ...
1282842  1598880599860 -163.30000    27.9 -61.200000
1282843  1598880599900 -163.30000    28.0 -61.200000
1282844  1598880599938 -163.30000    27.9 -61.300000
1282845  1598880599958 -163.30000    27.9 -61.300000
1282846  1598880599998 -163.40001    28.0 -61.300000

[1282847 rows x 4 columns]

In [14]:
df = pd.read_csv(dir_name+"1598832660_mGyr.csv")
df['timestamp_s']=df['timestamp_s'].astype('int64')
df['timestamp']=df['timestamp']*1000
df['timestamp']=df['timestamp'].astype('int64')
df['timestamp_s']=df['timestamp_s']*1000
df['timestamp']=df['timestamp_s']+df['timestamp']
df.drop(columns=['timestamp_s'],inplace=True)
df.to_csv(dir_name+"1598832660_mGyr.csv",index=False)
df

,timestamp,mGyr_x,mGyr_y,mGyr_z,mGyr_roll,mGyr_pitch,mGyr_yaw
0,1598832660018,0.000300,0.000497,-0.000398,7.329460e-09,-4.426525e-09,5.877992e-09
1,1598832660062,-0.002144,0.000497,-0.000398,2.328895e-08,1.005177e-07,1.867699e-08
2,1598832660091,-0.000922,-0.000114,0.000823,-2.973670e-09,2.399609e-08,-2.143587e-08
3,1598832660132,0.004576,-0.000114,0.001434,-1.149149e-08,-4.603344e-07,-1.442885e-07
4,1598832660152,0.000911,0.001718,0.002045,8.136358e-08,-4.312589e-08,-9.683799e-08
...,...,...,...,...,...,...,...
1284009,1598880599861,0.000129,-0.000124,-0.001205,-3.800494e-09,-3.950267e-09,3.691908e-08
1284010,1598880599900,0.000740,-0.000124,0.000017,-1.560923e-09,-9.311712e-09,-2.152997e-10
1284011,1598880599939,0.001351,0.001098,-0.001205,3.898228e-08,-4.796317e-08,4.277855e-08
1284012,1598880599959,-0.001704,0.000487,-0.001205,1.750112e-08,6.124296e-08,4.330266e-08
1284013,1598880599999,-0.001704,0.001098,0.000017,3.732700e-08,5.793268e-08,-5.816127e-10

In [15]:
df = pd.read_csv(dir_name+"1598832660_mGps.csv")
df['timestamp_s']=df['timestamp_s'].astype('int64')
df['timestamp']=df['timestamp']*1000
df['timestamp']=df['timestamp'].astype('int64')
df['timestamp_s']=df['timestamp_s']*1000
df['timestamp']=df['timestamp_s']+df['timestamp']
df.drop(columns=['timestamp_s'],inplace=True)
df.to_csv(dir_name+"1598832660_mGps.csv",index=False)
df

           timestamp   mGps_lat    mGps_lon  mGps_accr
0      1598832667000  37.482426  126.956290     12.425
1      1598832677000  37.482423  126.956288     12.335
2      1598832687000  37.482443  126.956309     16.144
3      1598832697000  37.482430  126.956295     12.027
4      1598832707000  37.482441  126.956304     11.825
...              ...        ...         ...        ...
11306  1598880585000  37.482462  126.956342     16.157
11307  1598880588000  37.482462  126.956317     15.152
11308  1598880591000  37.482470  126.956347     14.901
11309  1598880594000  37.482482  126.956366     14.901
11310  1598880597000  37.482494  126.956373     15.899

[11311 rows x 4 columns]

In [16]:
df = pd.read_csv(dir_name+"1598832660_e4Acc.csv")
df['timestamp_s']=df['timestamp_s'].astype('int64')
df['timestamp']=df['timestamp']*1000
df['timestamp']=df['timestamp'].astype('int64')
df['timestamp_s']=df['timestamp_s']*1000
df['timestamp']=df['timestamp_s']+df['timestamp']
df.drop(columns=['timestamp_s'],inplace=True)
df.to_csv(dir_name+"1598832660_e4Acc.csv",index=False)
df

            timestamp   e4Acc_x   e4Acc_y   e4Acc_z
0       1598833283000 -0.484375 -0.375000 -0.703125
1       1598833283031 -0.593750 -0.312500 -0.937500
2       1598833283062 -0.890625 -0.609375 -1.140625
3       1598833283093 -0.796875 -0.718750 -0.937500
4       1598833283125 -0.843750 -0.593750 -0.875000
...               ...       ...       ...       ...
223351  1598880599843 -0.859375 -0.453125 -0.328125
223352  1598880599875 -0.843750 -0.437500 -0.343750
223353  1598880599906 -0.828125 -0.453125 -0.375000
223354  1598880599937 -0.750000 -0.453125 -0.343750
223355  1598880599968 -0.781250 -0.453125 -0.375000

[223356 rows x 4 columns]

In [17]:
df = pd.read_csv(dir_name+"1598832660_e4Bvp.csv")
df['timestamp_s']=df['timestamp_s'].astype('int64')
df['timestamp']=df['timestamp']*1000
df['timestamp']=df['timestamp'].astype('int64')
df['timestamp_s']=df['timestamp_s']*1000
df['timestamp']=df['timestamp_s']+df['timestamp']
df.drop(columns=['timestamp_s'],inplace=True)
df.to_csv(dir_name+"1598832660_e4Bvp.csv",index=False)
df

            timestamp  e4Bvp_val
0       1598833283171       0.01
1       1598833283187       0.01
2       1598833283218      -0.03
3       1598833283234      -0.05
4       1598833283250      -0.05
...               ...        ...
446635  1598880599921     -11.92
446636  1598880599937     -10.91
446637  1598880599953      -8.90
446638  1598880599968      -4.88
446639  1598880599984       1.01

[446640 rows x 2 columns]

In [18]:
df = pd.read_csv(dir_name+"1598832660_e4Eda.csv")
df['timestamp_s']=df['timestamp_s'].astype('int64')
df['timestamp']=df['timestamp']*1000
df['timestamp']=df['timestamp'].astype('int64')
df['timestamp_s']=df['timestamp_s']*1000
df['timestamp']=df['timestamp_s']+df['timestamp']
df.drop(columns=['timestamp_s'],inplace=True)
df.to_csv(dir_name+"1598832660_e4Eda.csv",index=False)
df

           timestamp  e4Eda_val
0      1598833283250   0.370126
1      1598833283500   0.358600
2      1598833283750   0.413671
3      1598833284000   0.502040
4      1598833284250   0.490514
...              ...        ...
27905  1598880598750  33.956406
27906  1598880599000  33.455372
27907  1598880599250  33.519569
27908  1598880599500  33.527256
27909  1598880599750  32.954777

[27910 rows x 2 columns]

In [19]:
df = pd.read_csv(dir_name+"1598832660_e4Hr.csv")
df['timestamp_s']=df['timestamp_s'].astype('int64')
df['timestamp']=df['timestamp']*1000
df['timestamp']=df['timestamp'].astype('int64')
df['timestamp_s']=df['timestamp_s']*1000
df['timestamp']=df['timestamp_s']+df['timestamp']
df.drop(columns=['timestamp_s'],inplace=True)
df.to_csv(dir_name+"1598832660_e4Hr.csv",index=False)
df

          timestamp  e4Hr_val
0     1598833293000     74.00
1     1598833294000     69.00
2     1598833295000     74.33
3     1598833296000     89.00
4     1598833297000     93.80
...             ...       ...
6956  1598880595000     84.50
6957  1598880596000     84.42
6958  1598880597000     84.32
6959  1598880598000     84.22
6960  1598880599000     84.12

[6961 rows x 2 columns]

In [20]:
df = pd.read_csv(dir_name+"1598832660_e4Temp.csv")
df['timestamp_s']=df['timestamp_s'].astype('int64')
df['timestamp']=df['timestamp']*1000
df['timestamp']=df['timestamp'].astype('int64')
df['timestamp_s']=df['timestamp_s']*1000
df['timestamp']=df['timestamp_s']+df['timestamp']
df.drop(columns=['timestamp_s'],inplace=True)
df.to_csv(dir_name+"1598832660_e4Temp.csv",index=False)
df

           timestamp  e4Temp_val
0      1598833283000       33.87
1      1598833283250       33.87
2      1598833283500       33.87
3      1598833283750       33.87
4      1598833284000       33.87
...              ...         ...
27911  1598880598750       33.91
27912  1598880599000       33.91
27913  1598880599250       33.91
27914  1598880599500       33.91
27915  1598880599750       33.91

[27916 rows x 2 columns]

In [21]:
import pandas as pd
import os
mAcc = pd.read_csv(dir_name+"1598832660_mAcc.csv")
mAcc['timestamp']=mAcc['timestamp'].astype('int64')
mMag = pd.read_csv(dir_name+"1598832660_mMag.csv")
mMag['timestamp']=mMag['timestamp'].astype('int64')
combined_csv = pd.merge_asof(mAcc, mMag, on='timestamp',direction='nearest')
combined_csv

,timestamp,mAcc_x,mAcc_y,mAcc_z,mMag_x,mMag_y,mMag_z
0,1598832660004,0.069434,-0.069434,9.703996,-11.2,-15.7,-70.900000
1,1598832660016,0.079011,-0.062251,9.701602,-11.2,-15.7,-70.900000
2,1598832660051,0.079011,-0.081405,9.696813,-11.2,-15.8,-70.800000
3,1598832660082,0.086194,-0.071828,9.682447,-11.1,-15.7,-70.800000
4,1598832660121,0.074223,-0.086194,9.718362,-11.2,-15.8,-70.700005
...,...,...,...,...,...,...,...
1292247,1598879919387,5.399090,0.081405,8.087860,-164.5,28.5,-57.800000
1292248,1598879919420,5.399090,0.064645,8.097438,-164.5,28.5,-57.800000
1292249,1598879919447,5.389513,0.062251,8.075889,-164.5,28.5,-57.800000
1292250,1598879919488,5.389513,0.069434,8.075889,-164.5,28.5,-57.700000
1292251,1598879919517,5.394301,0.088588,8.083072,-164.5,28.5,-57.700000

In [22]:
mGyr = pd.read_csv(dir_name+"1598832660_mGyr.csv")

combined_csv = pd.merge_asof(combined_csv, mGyr, on='timestamp',direction='nearest')
combined_csv

,timestamp,mAcc_x,mAcc_y,mAcc_z,mMag_x,mMag_y,mMag_z,mGyr_x,mGyr_y,mGyr_z,mGyr_roll,mGyr_pitch,mGyr_yaw
0,1598832660004,0.069434,-0.069434,9.703996,-11.2,-15.7,-70.900000,0.000300,0.000497,-0.000398,7.329460e-09,-4.426525e-09,5.877992e-09
1,1598832660016,0.079011,-0.062251,9.701602,-11.2,-15.7,-70.900000,0.000300,0.000497,-0.000398,7.329460e-09,-4.426525e-09,5.877992e-09
2,1598832660051,0.079011,-0.081405,9.696813,-11.2,-15.8,-70.800000,-0.002144,0.000497,-0.000398,2.328895e-08,1.005177e-07,1.867699e-08
3,1598832660082,0.086194,-0.071828,9.682447,-11.1,-15.7,-70.800000,-0.000922,-0.000114,0.000823,-2.973670e-09,2.399609e-08,-2.143587e-08
4,1598832660121,0.074223,-0.086194,9.718362,-11.2,-15.8,-70.700005,0.004576,-0.000114,0.001434,-1.149149e-08,-4.603344e-07,-1.442885e-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1292247,1598879919387,5.399090,0.081405,8.087860,-164.5,28.5,-57.800000,-0.002217,0.001234,0.000420,5.323967e-08,9.564692e-08,-1.813312e-08
1292248,1598879919420,5.399090,0.064645,8.097438,-164.5,28.5,-57.800000,-0.002217,0.001234,0.000420,5.323967e-08,9.564692e-08,-1.813312e-08
1292249,1598879919447,5.389513,0.062251,8.075889,-164.5,28.5,-57.800000,0.002059,0.000012,0.001031,4.720500e-10,-7.956429e-08,-3.984115e-08
1292250,1598879919488,5.389513,0.069434,8.075889,-164.5,28.5,-57.700000,-0.000384,0.001234,0.002253,5.376874e-08,1.674284e-08,-9.816788e-08
1292251,1598879919517,5.394301,0.088588,8.083072,-164.5,28.5,-57.700000,-0.000384,0.001234,0.002253,5.376874e-08,1.674284e-08,-9.816788e-08

In [23]:
mGps = pd.read_csv(dir_name+"1598832660_mGps.csv")

combined_csv = pd.merge_asof(combined_csv, mGps, on='timestamp',direction='nearest')
combined_csv

,timestamp,mAcc_x,mAcc_y,mAcc_z,mMag_x,mMag_y,mMag_z,mGyr_x,mGyr_y,mGyr_z,mGyr_roll,mGyr_pitch,mGyr_yaw,mGps_lat,mGps_lon,mGps_accr
0,1598832660004,0.069434,-0.069434,9.703996,-11.2,-15.7,-70.900000,0.000300,0.000497,-0.000398,7.329460e-09,-4.426525e-09,5.877992e-09,37.482426,126.956290,12.425
1,1598832660016,0.079011,-0.062251,9.701602,-11.2,-15.7,-70.900000,0.000300,0.000497,-0.000398,7.329460e-09,-4.426525e-09,5.877992e-09,37.482426,126.956290,12.425
2,1598832660051,0.079011,-0.081405,9.696813,-11.2,-15.8,-70.800000,-0.002144,0.000497,-0.000398,2.328895e-08,1.005177e-07,1.867699e-08,37.482426,126.956290,12.425
3,1598832660082,0.086194,-0.071828,9.682447,-11.1,-15.7,-70.800000,-0.000922,-0.000114,0.000823,-2.973670e-09,2.399609e-08,-2.143587e-08,37.482426,126.956290,12.425
4,1598832660121,0.074223,-0.086194,9.718362,-11.2,-15.8,-70.700005,0.004576,-0.000114,0.001434,-1.149149e-08,-4.603344e-07,-1.442885e-07,37.482426,126.956290,12.425
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1292247,1598879919387,5.399090,0.081405,8.087860,-164.5,28.5,-57.800000,-0.002217,0.001234,0.000420,5.323967e-08,9.564692e-08,-1.813312e-08,37.482434,126.956302,13.678
1292248,1598879919420,5.399090,0.064645,8.097438,-164.5,28.5,-57.800000,-0.002217,0.001234,0.000420,5.323967e-08,9.564692e-08,-1.813312e-08,37.482434,126.956302,13.678
1292249,1598879919447,5.389513,0.062251,8.075889,-164.5,28.5,-57.800000,0.002059,0.000012,0.001031,4.720500e-10,-7.956429e-08,-3.984115e-08,37.482434,126.956302,13.678
1292250,1598879919488,5.389513,0.069434,8.075889,-164.5,28.5,-57.700000,-0.000384,0.001234,0.002253,5.376874e-08,1.674284e-08,-9.816788e-08,37.482434,126.956302,13.678
1292251,1598879919517,5.394301,0.088588,8.083072,-164.5,28.5,-57.700000,-0.000384,0.001234,0.002253,5.376874e-08,1.674284e-08,-9.816788e-08,37.482434,126.956302,13.678

In [24]:
#combined_csv = pd.read_csv(dir_name+"1598832660_combined.csv")
e4Acc = pd.read_csv(dir_name+"1598832660_e4Acc.csv")

combined_csv = pd.merge_asof(combined_csv, e4Acc, on='timestamp',direction='nearest')
combined_csv

,timestamp,mAcc_x,mAcc_y,mAcc_z,mMag_x,mMag_y,mMag_z,mGyr_x,mGyr_y,mGyr_z,mGyr_roll,mGyr_pitch,mGyr_yaw,mGps_lat,mGps_lon,mGps_accr,e4Acc_x,e4Acc_y,e4Acc_z
0,1598832660004,0.069434,-0.069434,9.703996,-11.2,-15.7,-70.900000,0.000300,0.000497,-0.000398,7.329460e-09,-4.426525e-09,5.877992e-09,37.482426,126.956290,12.425,-0.484375,-0.375000,-0.703125
1,1598832660016,0.079011,-0.062251,9.701602,-11.2,-15.7,-70.900000,0.000300,0.000497,-0.000398,7.329460e-09,-4.426525e-09,5.877992e-09,37.482426,126.956290,12.425,-0.484375,-0.375000,-0.703125
2,1598832660051,0.079011,-0.081405,9.696813,-11.2,-15.8,-70.800000,-0.002144,0.000497,-0.000398,2.328895e-08,1.005177e-07,1.867699e-08,37.482426,126.956290,12.425,-0.484375,-0.375000,-0.703125
3,1598832660082,0.086194,-0.071828,9.682447,-11.1,-15.7,-70.800000,-0.000922,-0.000114,0.000823,-2.973670e-09,2.399609e-08,-2.143587e-08,37.482426,126.956290,12.425,-0.484375,-0.375000,-0.703125
4,1598832660121,0.074223,-0.086194,9.718362,-11.2,-15.8,-70.700005,0.004576,-0.000114,0.001434,-1.149149e-08,-4.603344e-07,-1.442885e-07,37.482426,126.956290,12.425,-0.484375,-0.375000,-0.703125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1292247,1598879919387,5.399090,0.081405,8.087860,-164.5,28.5,-57.800000,-0.002217,0.001234,0.000420,5.323967e-08,9.564692e-08,-1.813312e-08,37.482434,126.956302,13.678,-0.343750,0.015625,0.937500
1292248,1598879919420,5.399090,0.064645,8.097438,-164.5,28.5,-57.800000,-0.002217,0.001234,0.000420,5.323967e-08,9.564692e-08,-1.813312e-08,37.482434,126.956302,13.678,-0.437500,0.031250,0.890625
1292249,1598879919447,5.389513,0.062251,8.075889,-164.5,28.5,-57.800000,0.002059,0.000012,0.001031,4.720500e-10,-7.956429e-08,-3.984115e-08,37.482434,126.956302,13.678,-0.375000,0.000000,0.921875
1292250,1598879919488,5.389513,0.069434,8.075889,-164.5,28.5,-57.700000,-0.000384,0.001234,0.002253,5.376874e-08,1.674284e-08,-9.816788e-08,37.482434,126.956302,13.678,-0.296875,0.046875,0.953125
1292251,1598879919517,5.394301,0.088588,8.083072,-164.5,28.5,-57.700000,-0.000384,0.001234,0.002253,5.376874e-08,1.674284e-08,-9.816788e-08,37.482434,126.956302,13.678,-0.546875,0.015625,0.859375

In [25]:
#combined_csv = pd.read_csv(dir_name+"1598832660_combined.csv")
e4Bvp = pd.read_csv(dir_name+"1598832660_e4Bvp.csv")

combined_csv = pd.merge_asof(combined_csv, e4Bvp, on='timestamp',direction='nearest')
combined_csv

,timestamp,mAcc_x,mAcc_y,mAcc_z,mMag_x,mMag_y,mMag_z,mGyr_x,mGyr_y,mGyr_z,mGyr_roll,mGyr_pitch,mGyr_yaw,mGps_lat,mGps_lon,mGps_accr,e4Acc_x,e4Acc_y,e4Acc_z,e4Bvp_val
0,1598832660004,0.069434,-0.069434,9.703996,-11.2,-15.7,-70.900000,0.000300,0.000497,-0.000398,7.329460e-09,-4.426525e-09,5.877992e-09,37.482426,126.956290,12.425,-0.484375,-0.375000,-0.703125,0.01
1,1598832660016,0.079011,-0.062251,9.701602,-11.2,-15.7,-70.900000,0.000300,0.000497,-0.000398,7.329460e-09,-4.426525e-09,5.877992e-09,37.482426,126.956290,12.425,-0.484375,-0.375000,-0.703125,0.01
2,1598832660051,0.079011,-0.081405,9.696813,-11.2,-15.8,-70.800000,-0.002144,0.000497,-0.000398,2.328895e-08,1.005177e-07,1.867699e-08,37.482426,126.956290,12.425,-0.484375,-0.375000,-0.703125,0.01
3,1598832660082,0.086194,-0.071828,9.682447,-11.1,-15.7,-70.800000,-0.000922,-0.000114,0.000823,-2.973670e-09,2.399609e-08,-2.143587e-08,37.482426,126.956290,12.425,-0.484375,-0.375000,-0.703125,0.01
4,1598832660121,0.074223,-0.086194,9.718362,-11.2,-15.8,-70.700005,0.004576,-0.000114,0.001434,-1.149149e-08,-4.603344e-07,-1.442885e-07,37.482426,126.956290,12.425,-0.484375,-0.375000,-0.703125,0.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1292247,1598879919387,5.399090,0.081405,8.087860,-164.5,28.5,-57.800000,-0.002217,0.001234,0.000420,5.323967e-08,9.564692e-08,-1.813312e-08,37.482434,126.956302,13.678,-0.343750,0.015625,0.937500,-53.53
1292248,1598879919420,5.399090,0.064645,8.097438,-164.5,28.5,-57.800000,-0.002217,0.001234,0.000420,5.323967e-08,9.564692e-08,-1.813312e-08,37.482434,126.956302,13.678,-0.437500,0.031250,0.890625,-48.04
1292249,1598879919447,5.389513,0.062251,8.075889,-164.5,28.5,-57.800000,0.002059,0.000012,0.001031,4.720500e-10,-7.956429e-08,-3.984115e-08,37.482434,126.956302,13.678,-0.375000,0.000000,0.921875,-42.64
1292250,1598879919488,5.389513,0.069434,8.075889,-164.5,28.5,-57.700000,-0.000384,0.001234,0.002253,5.376874e-08,1.674284e-08,-9.816788e-08,37.482434,126.956302,13.678,-0.296875,0.046875,0.953125,-35.11
1292251,1598879919517,5.394301,0.088588,8.083072,-164.5,28.5,-57.700000,-0.000384,0.001234,0.002253,5.376874e-08,1.674284e-08,-9.816788e-08,37.482434,126.956302,13.678,-0.546875,0.015625,0.859375,-28.41

In [26]:
#combined_csv = pd.read_csv(dir_name+"1598832660_combined.csv")
e4Temp = pd.read_csv(dir_name+"1598832660_e4Temp.csv")

combined_csv = pd.merge_asof(combined_csv, e4Temp, on='timestamp',direction='nearest')
combined_csv

,timestamp,mAcc_x,mAcc_y,mAcc_z,mMag_x,mMag_y,mMag_z,mGyr_x,mGyr_y,mGyr_z,...,mGyr_pitch,mGyr_yaw,mGps_lat,mGps_lon,mGps_accr,e4Acc_x,e4Acc_y,e4Acc_z,e4Bvp_val,e4Temp_val
0,1598832660004,0.069434,-0.069434,9.703996,-11.2,-15.7,-70.900000,0.000300,0.000497,-0.000398,...,-4.426525e-09,5.877992e-09,37.482426,126.956290,12.425,-0.484375,-0.375000,-0.703125,0.01,33.87
1,1598832660016,0.079011,-0.062251,9.701602,-11.2,-15.7,-70.900000,0.000300,0.000497,-0.000398,...,-4.426525e-09,5.877992e-09,37.482426,126.956290,12.425,-0.484375,-0.375000,-0.703125,0.01,33.87
2,1598832660051,0.079011,-0.081405,9.696813,-11.2,-15.8,-70.800000,-0.002144,0.000497,-0.000398,...,1.005177e-07,1.867699e-08,37.482426,126.956290,12.425,-0.484375,-0.375000,-0.703125,0.01,33.87
3,1598832660082,0.086194,-0.071828,9.682447,-11.1,-15.7,-70.800000,-0.000922,-0.000114,0.000823,...,2.399609e-08,-2.143587e-08,37.482426,126.956290,12.425,-0.484375,-0.375000,-0.703125,0.01,33.87
4,1598832660121,0.074223,-0.086194,9.718362,-11.2,-15.8,-70.700005,0.004576,-0.000114,0.001434,...,-4.603344e-07,-1.442885e-07,37.482426,126.956290,12.425,-0.484375,-0.375000,-0.703125,0.01,33.87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1292247,1598879919387,5.399090,0.081405,8.087860,-164.5,28.5,-57.800000,-0.002217,0.001234,0.000420,...,9.564692e-08,-1.813312e-08,37.482434,126.956302,13.678,-0.343750,0.015625,0.937500,-53.53,34.15
1292248,1598879919420,5.399090,0.064645,8.097438,-164.5,28.5,-57.800000,-0.002217,0.001234,0.000420,...,9.564692e-08,-1.813312e-08,37.482434,126.956302,13.678,-0.437500,0.031250,0.890625,-48.04,34.15
1292249,1598879919447,5.389513,0.062251,8.075889,-164.5,28.5,-57.800000,0.002059,0.000012,0.001031,...,-7.956429e-08,-3.984115e-08,37.482434,126.956302,13.678,-0.375000,0.000000,0.921875,-42.64,34.15
1292250,1598879919488,5.389513,0.069434,8.075889,-164.5,28.5,-57.700000,-0.000384,0.001234,0.002253,...,1.674284e-08,-9.816788e-08,37.482434,126.956302,13.678,-0.296875,0.046875,0.953125,-35.11,34.15
1292251,1598879919517,5.394301,0.088588,8.083072,-164.5,28.5,-57.700000,-0.000384,0.001234,0.002253,...,1.674284e-08,-9.816788e-08,37.482434,126.956302,13.678,-0.546875,0.015625,0.859375,-28.41,34.15

In [27]:
#combined_csv = pd.read_csv(dir_name+"1598832660_combined.csv")
e4Hr = pd.read_csv(dir_name+"1598832660_e4Hr.csv")

combined_csv = pd.merge_asof(combined_csv, e4Hr, on='timestamp',direction='nearest')
combined_csv

,timestamp,mAcc_x,mAcc_y,mAcc_z,mMag_x,mMag_y,mMag_z,mGyr_x,mGyr_y,mGyr_z,...,mGyr_yaw,mGps_lat,mGps_lon,mGps_accr,e4Acc_x,e4Acc_y,e4Acc_z,e4Bvp_val,e4Temp_val,e4Hr_val
0,1598832660004,0.069434,-0.069434,9.703996,-11.2,-15.7,-70.900000,0.000300,0.000497,-0.000398,...,5.877992e-09,37.482426,126.956290,12.425,-0.484375,-0.375000,-0.703125,0.01,33.87,74.00
1,1598832660016,0.079011,-0.062251,9.701602,-11.2,-15.7,-70.900000,0.000300,0.000497,-0.000398,...,5.877992e-09,37.482426,126.956290,12.425,-0.484375,-0.375000,-0.703125,0.01,33.87,74.00
2,1598832660051,0.079011,-0.081405,9.696813,-11.2,-15.8,-70.800000,-0.002144,0.000497,-0.000398,...,1.867699e-08,37.482426,126.956290,12.425,-0.484375,-0.375000,-0.703125,0.01,33.87,74.00
3,1598832660082,0.086194,-0.071828,9.682447,-11.1,-15.7,-70.800000,-0.000922,-0.000114,0.000823,...,-2.143587e-08,37.482426,126.956290,12.425,-0.484375,-0.375000,-0.703125,0.01,33.87,74.00
4,1598832660121,0.074223,-0.086194,9.718362,-11.2,-15.8,-70.700005,0.004576,-0.000114,0.001434,...,-1.442885e-07,37.482426,126.956290,12.425,-0.484375,-0.375000,-0.703125,0.01,33.87,74.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1292247,1598879919387,5.399090,0.081405,8.087860,-164.5,28.5,-57.800000,-0.002217,0.001234,0.000420,...,-1.813312e-08,37.482434,126.956302,13.678,-0.343750,0.015625,0.937500,-53.53,34.15,82.10
1292248,1598879919420,5.399090,0.064645,8.097438,-164.5,28.5,-57.800000,-0.002217,0.001234,0.000420,...,-1.813312e-08,37.482434,126.956302,13.678,-0.437500,0.031250,0.890625,-48.04,34.15,82.10
1292249,1598879919447,5.389513,0.062251,8.075889,-164.5,28.5,-57.800000,0.002059,0.000012,0.001031,...,-3.984115e-08,37.482434,126.956302,13.678,-0.375000,0.000000,0.921875,-42.64,34.15,82.10
1292250,1598879919488,5.389513,0.069434,8.075889,-164.5,28.5,-57.700000,-0.000384,0.001234,0.002253,...,-9.816788e-08,37.482434,126.956302,13.678,-0.296875,0.046875,0.953125,-35.11,34.15,82.10
1292251,1598879919517,5.394301,0.088588,8.083072,-164.5,28.5,-57.700000,-0.000384,0.001234,0.002253,...,-9.816788e-08,37.482434,126.956302,13.678,-0.546875,0.015625,0.859375,-28.41,34.15,82.25

In [28]:
#combined_csv = pd.read_csv(dir_name+"1598832660_combined.csv")
e4Eda = pd.read_csv(dir_name+"1598832660_e4Eda.csv")

combined_csv = pd.merge_asof(combined_csv, e4Eda, on='timestamp',direction='nearest')
combined_csv

,timestamp,mAcc_x,mAcc_y,mAcc_z,mMag_x,mMag_y,mMag_z,mGyr_x,mGyr_y,mGyr_z,...,mGps_lat,mGps_lon,mGps_accr,e4Acc_x,e4Acc_y,e4Acc_z,e4Bvp_val,e4Temp_val,e4Hr_val,e4Eda_val
0,1598832660004,0.069434,-0.069434,9.703996,-11.2,-15.7,-70.900000,0.000300,0.000497,-0.000398,...,37.482426,126.956290,12.425,-0.484375,-0.375000,-0.703125,0.01,33.87,74.00,0.370126
1,1598832660016,0.079011,-0.062251,9.701602,-11.2,-15.7,-70.900000,0.000300,0.000497,-0.000398,...,37.482426,126.956290,12.425,-0.484375,-0.375000,-0.703125,0.01,33.87,74.00,0.370126
2,1598832660051,0.079011,-0.081405,9.696813,-11.2,-15.8,-70.800000,-0.002144,0.000497,-0.000398,...,37.482426,126.956290,12.425,-0.484375,-0.375000,-0.703125,0.01,33.87,74.00,0.370126
3,1598832660082,0.086194,-0.071828,9.682447,-11.1,-15.7,-70.800000,-0.000922,-0.000114,0.000823,...,37.482426,126.956290,12.425,-0.484375,-0.375000,-0.703125,0.01,33.87,74.00,0.370126
4,1598832660121,0.074223,-0.086194,9.718362,-11.2,-15.8,-70.700005,0.004576,-0.000114,0.001434,...,37.482426,126.956290,12.425,-0.484375,-0.375000,-0.703125,0.01,33.87,74.00,0.370126
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1292247,1598879919387,5.399090,0.081405,8.087860,-164.5,28.5,-57.800000,-0.002217,0.001234,0.000420,...,37.482434,126.956302,13.678,-0.343750,0.015625,0.937500,-53.53,34.15,82.10,28.919807
1292248,1598879919420,5.399090,0.064645,8.097438,-164.5,28.5,-57.800000,-0.002217,0.001234,0.000420,...,37.482434,126.956302,13.678,-0.437500,0.031250,0.890625,-48.04,34.15,82.10,28.919807
1292249,1598879919447,5.389513,0.062251,8.075889,-164.5,28.5,-57.800000,0.002059,0.000012,0.001031,...,37.482434,126.956302,13.678,-0.375000,0.000000,0.921875,-42.64,34.15,82.10,28.919807
1292250,1598879919488,5.389513,0.069434,8.075889,-164.5,28.5,-57.700000,-0.000384,0.001234,0.002253,...,37.482434,126.956302,13.678,-0.296875,0.046875,0.953125,-35.11,34.15,82.10,28.919807
1292251,1598879919517,5.394301,0.088588,8.083072,-164.5,28.5,-57.700000,-0.000384,0.001234,0.002253,...,37.482434,126.956302,13.678,-0.546875,0.015625,0.859375,-28.41,34.15,82.25,28.919807

In [29]:
labels = pd.read_csv(dir_name+"1598832660_label.csv")
labels.rename(columns={'ts':'timestamp'},inplace='True')
labels['timestamp']=labels['timestamp'].astype('int64')
labels['timestamp']=labels['timestamp']*1000
labels

,timestamp,action,actionOption,actionSub,actionSubOption,condition,conditionSub1Option,conditionSub2Option,place,emotionPositive,emotionTension,activity
0,1598832660000,household,43,NaN,NaN,ALONE,NaN,NaN,home,7,3,3
1,1598832720000,household,43,NaN,NaN,ALONE,NaN,NaN,home,7,3,3
2,1598832780000,household,43,NaN,NaN,ALONE,NaN,NaN,home,7,3,3
3,1598832840000,household,43,NaN,NaN,ALONE,NaN,NaN,home,7,3,3
4,1598832900000,household,43,NaN,NaN,ALONE,NaN,NaN,home,7,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...
774,1598880300000,study,313,NaN,NaN,ALONE,NaN,NaN,home,7,2,3
775,1598880360000,study,313,NaN,NaN,ALONE,NaN,NaN,home,7,2,3
776,1598880420000,study,313,NaN,NaN,ALONE,NaN,NaN,home,7,2,3
777,1598880480000,study,313,NaN,NaN,ALONE,NaN,NaN,home,7,2,3
778,1598880540000,study,313,NaN,NaN,ALONE,NaN,NaN,home,7,2,3

In [30]:
combined_csv = pd.merge_asof(combined_csv, labels, on='timestamp',direction='nearest')
combined_csv

,timestamp,mAcc_x,mAcc_y,mAcc_z,mMag_x,mMag_y,mMag_z,mGyr_x,mGyr_y,mGyr_z,...,actionOption,actionSub,actionSubOption,condition,conditionSub1Option,conditionSub2Option,place,emotionPositive,emotionTension,activity
0,1598832660004,0.069434,-0.069434,9.703996,-11.2,-15.7,-70.900000,0.000300,0.000497,-0.000398,...,43,NaN,NaN,ALONE,NaN,NaN,home,7,3,3
1,1598832660016,0.079011,-0.062251,9.701602,-11.2,-15.7,-70.900000,0.000300,0.000497,-0.000398,...,43,NaN,NaN,ALONE,NaN,NaN,home,7,3,3
2,1598832660051,0.079011,-0.081405,9.696813,-11.2,-15.8,-70.800000,-0.002144,0.000497,-0.000398,...,43,NaN,NaN,ALONE,NaN,NaN,home,7,3,3
3,1598832660082,0.086194,-0.071828,9.682447,-11.1,-15.7,-70.800000,-0.000922,-0.000114,0.000823,...,43,NaN,NaN,ALONE,NaN,NaN,home,7,3,3
4,1598832660121,0.074223,-0.086194,9.718362,-11.2,-15.8,-70.700005,0.004576,-0.000114,0.001434,...,43,NaN,NaN,ALONE,NaN,NaN,home,7,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1292247,1598879919387,5.399090,0.081405,8.087860,-164.5,28.5,-57.800000,-0.002217,0.001234,0.000420,...,313,NaN,NaN,ALONE,NaN,NaN,home,7,2,3
1292248,1598879919420,5.399090,0.064645,8.097438,-164.5,28.5,-57.800000,-0.002217,0.001234,0.000420,...,313,NaN,NaN,ALONE,NaN,NaN,home,7,2,3
1292249,1598879919447,5.389513,0.062251,8.075889,-164.5,28.5,-57.800000,0.002059,0.000012,0.001031,...,313,NaN,NaN,ALONE,NaN,NaN,home,7,2,3
1292250,1598879919488,5.389513,0.069434,8.075889,-164.5,28.5,-57.700000,-0.000384,0.001234,0.002253,...,313,NaN,NaN,ALONE,NaN,NaN,home,7,2,3
1292251,1598879919517,5.394301,0.088588,8.083072,-164.5,28.5,-57.700000,-0.000384,0.001234,0.002253,...,313,NaN,NaN,ALONE,NaN,NaN,home,7,2,3

In [31]:
combined_csv.columns

Index(['timestamp', 'mAcc_x', 'mAcc_y', 'mAcc_z', 'mMag_x', 'mMag_y', 'mMag_z',
       'mGyr_x', 'mGyr_y', 'mGyr_z', 'mGyr_roll', 'mGyr_pitch', 'mGyr_yaw',
       'mGps_lat', 'mGps_lon', 'mGps_accr', 'e4Acc_x', 'e4Acc_y', 'e4Acc_z',
       'e4Bvp_val', 'e4Temp_val', 'e4Hr_val', 'e4Eda_val', 'action',
       'actionOption', 'actionSub', 'actionSubOption', 'condition',
       'conditionSub1Option', 'conditionSub2Option', 'place',
       'emotionPositive', 'emotionTension', 'activity'],
      dtype='object')

In [58]:
combined_csv.drop(columns=['actionOption','actionSub', 'actionSubOption', 'condition', 'conditionSub1Option',
      'conditionSub2Option','place','emotionPositive', 'emotionTension','activity','mGps_accr'], inplace=True)
combined_csv = combined_csv.iloc[::32, :]      
combined_csv['date_time'] = pd.to_datetime(combined_csv['timestamp'], unit='ms').dt.tz_localize('UTC').dt.tz_convert('Asia/Seoul').dt.tz_localize(None)
combined_csv.to_csv(dir_name+"1598832660_combined.csv",index=False)
combined_csv

,timestamp,mAcc_x,mAcc_y,mAcc_z,mMag_x,mMag_y,mMag_z,mGyr_x,mGyr_y,mGyr_z,...,mGps_lon,e4Acc_x,e4Acc_y,e4Acc_z,e4Bvp_val,e4Temp_val,e4Hr_val,e4Eda_val,action,date_time
0,1598832660004,0.069434,-0.069434,9.703996,-11.2,-15.7,-70.900000,0.000300,0.000497,-0.000398,...,126.956290,-0.484375,-0.375000,-0.703125,0.01,33.87,74.00,0.370126,household,2020-08-31 09:11:00.004
1,1598832660016,0.079011,-0.062251,9.701602,-11.2,-15.7,-70.900000,0.000300,0.000497,-0.000398,...,126.956290,-0.484375,-0.375000,-0.703125,0.01,33.87,74.00,0.370126,household,2020-08-31 09:11:00.016
2,1598832660051,0.079011,-0.081405,9.696813,-11.2,-15.8,-70.800000,-0.002144,0.000497,-0.000398,...,126.956290,-0.484375,-0.375000,-0.703125,0.01,33.87,74.00,0.370126,household,2020-08-31 09:11:00.051
3,1598832660082,0.086194,-0.071828,9.682447,-11.1,-15.7,-70.800000,-0.000922,-0.000114,0.000823,...,126.956290,-0.484375,-0.375000,-0.703125,0.01,33.87,74.00,0.370126,household,2020-08-31 09:11:00.082
4,1598832660121,0.074223,-0.086194,9.718362,-11.2,-15.8,-70.700005,0.004576,-0.000114,0.001434,...,126.956290,-0.484375,-0.375000,-0.703125,0.01,33.87,74.00,0.370126,household,2020-08-31 09:11:00.121
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1292247,1598879919387,5.399090,0.081405,8.087860,-164.5,28.5,-57.800000,-0.002217,0.001234,0.000420,...,126.956302,-0.343750,0.015625,0.937500,-53.53,34.15,82.10,28.919807,study,2020-08-31 22:18:39.387
1292248,1598879919420,5.399090,0.064645,8.097438,-164.5,28.5,-57.800000,-0.002217,0.001234,0.000420,...,126.956302,-0.437500,0.031250,0.890625,-48.04,34.15,82.10,28.919807,study,2020-08-31 22:18:39.420
1292249,1598879919447,5.389513,0.062251,8.075889,-164.5,28.5,-57.800000,0.002059,0.000012,0.001031,...,126.956302,-0.375000,0.000000,0.921875,-42.64,34.15,82.10,28.919807,study,2020-08-31 22:18:39.447
1292250,1598879919488,5.389513,0.069434,8.075889,-164.5,28.5,-57.700000,-0.000384,0.001234,0.002253,...,126.956302,-0.296875,0.046875,0.953125,-35.11,34.15,82.10,28.919807,study,2020-08-31 22:18:39.488
1292251,1598879919517,5.394301,0.088588,8.083072,-164.5,28.5,-57.700000,-0.000384,0.001234,0.002253,...,126.956302,-0.546875,0.015625,0.859375,-28.41,34.15,82.25,28.919807,study,2020-08-31 22:18:39.517

In [59]:
combined_csv.action.unique()

array(['household', 'travel', 'personal_care', 'meal', 'recreation_media',
       'work', 'study'], dtype=object)

In [61]:
combined_csv.isna().sum()

timestamp     0
mAcc_x        0
mAcc_y        0
mAcc_z        0
mMag_x        0
mMag_y        0
mMag_z        0
mGyr_x        0
mGyr_y        0
mGyr_z        0
mGyr_roll     0
mGyr_pitch    0
mGyr_yaw      0
mGps_lat      0
mGps_lon      0
e4Acc_x       0
e4Acc_y       0
e4Acc_z       0
e4Bvp_val     0
e4Temp_val    0
e4Hr_val      0
e4Eda_val     0
action        0
date_time     0
dtype: int64

In [52]:
combined_csv.dtypes

timestamp                          int64
mAcc_x                           float64
mAcc_y                           float64
mAcc_z                           float64
mMag_x                           float64
mMag_y                           float64
mMag_z                           float64
mGyr_x                           float64
mGyr_y                           float64
mGyr_z                           float64
mGyr_roll                        float64
mGyr_pitch                       float64
mGyr_yaw                         float64
mGps_lat                         float64
mGps_lon                         float64
e4Acc_x                          float64
e4Acc_y                          float64
e4Acc_z                          float64
e4Bvp_val                        float64
e4Temp_val                       float64
e4Hr_val                         float64
e4Eda_val                        float64
action                            object
date_time     datetime64[ns, Asia/Seoul]
dtype: object